import React from "react";
import Head from "next/head";
import Layout from "../../Components/LayoutWrapper/Layout";
import HeaderBanner from "../../Components/HeaderBanner/HeaderBanner";
import Register from "../../Components/SignUp/Register";

export default function register_user() {
  return (
    <div>
      <Head>
        <title>Canada Freelancer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <HeaderBanner />
        <Register />
      </Layout>
    </div>
  );
}
