import React from "react";
import Head from "next/head";
import Layout from "../../Components/LayoutWrapper/Layout";
import HeaderBanner from "../../Components/HeaderBanner/HeaderBanner";
import Form from "../../Components/SignUp/Form";

export default function register_detials() {
  return (
    <>
      <Head>
        <title>Canada Freelancer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <HeaderBanner />
        <Form />
      </Layout>
    </>
  );
}
