import React from 'react'
import Info from "../components/How it works/Info";
import Head from "next/head";
import styles from "../styles/Info.module.css";
import NavBar from '../Components/Nav/NavBar';



function HowItWorksPage() {
  return (
      <div>
       <Head>
          <title>Canada Freelancer</title>
          <meta name="description" content="Generated by create next app"/>
        </Head>

      <header>
      <NavBar />
        <Info />
          
        </header>
        <main>
        </main>
      <footer>
     
        </footer>
         
     
           

    </div>
  )
}

export default HowItWorksPage