import React from "react";
import Head from "next/head";
import Login from "../components/Login/Login";



export default function LoginPage() {
    return (
      <div>
        <Head>
          <title>Canada Freelancer</title>
          <meta name="description" content="Generated by create next app"/>
        </Head>

        <header>
        <Login />
          
        </header>
        <main>
        </main>
        <footer>
        </footer>
      </div>
    );
  }
  
  