import React from "react";
import Head from "next/head";
import SignUpfreelancer from "../Components/SignUps/SignUpfreelancer";




  

export default function SignUpFreePage() {
  return (
    <div>
      <Head>
        <title>Canada Freelancer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
      <SignUpfreelancer />
        
      </header>
      <main>
      </main>
      <footer>
      </footer>
    </div>
  );
}