import React from "react";
import Head from "next/head";
import SignUpClient from "../Components/SignUps/SignUpClient";




  

export default function SignUpClientPage() {
  return (
    <div>
      <Head>
        <title>Canada Freelancer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
      <SignUpClient /> 
      </header>
      <main>
      </main>
      <footer>
      </footer>
    </div>
  );
}