import React from "react";
import Head from "next/head";
import SignUp from "../components/SignUp/SignUp";




  

export default function SignupPage() {
  return (
    <div>
      <Head>
        <title>Canada Freelancer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
      <SignUp />
        
      </header>
      <main>
      </main>
      <footer>
      </footer>
    </div>
  );
}
